name: morning my baby
on:
  schedule:
  - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send morning to your girlfriend

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: master

    - name: sender
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: pip install -r ./requirements.txt && python ./main.py

    env:
      APP_ID: wx896b943c9b8b7970
      APP_SECRET: ${{ secrets.APP_SECRET }}
      TEMPLATE_ID:jDF3QAB4mrmYIf7klevgtiWCsQCT1rt8TW01qyjM4GU
      USER_ID: ${{ secrets.USER_ID }}
      START_DATE: 2022.6.7
      BIRTHDAY: 2003.11.6
      CITY: lijiang
